run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - godot
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enable-all: false
    disabled-checks:
      - hugeParam
  revive:
    severity: warning
    rules:
      - name: exported
        disabled: true
      - name: if-return
      - name: indent-error-flow
      - name: superfluous-else
      - name: unexported-return
  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
  exclude-rules:
    # Allow benign unchecked returns for user-facing logging IO
    - text: "Error return value of `fmt\\.Fprint"
      linters: [errcheck]
    - text: "Error return value of `fmt\\.Fprintln"
      linters: [errcheck]
    - text: "Error return value of `fmt\\.Fprintf"
      linters: [errcheck]
    - text: "Error return value of `resp\\.Body\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `filepath\\.Abs`"
      linters: [errcheck]
    - text: "Error return value of `filepath\\.Rel`"
      linters: [errcheck]
    - text: "Error return value of `d\\.Info`"
      linters: [errcheck]
    - text: "Error return value of `http\\.NewRequest`"
      linters: [errcheck]
    # Best-effort operations that should be tolerant of failures
    - text: "Error return value of `cache\\.Load`"
      linters: [errcheck]
    - text: "Error return value of `cache\\.Save`"
      linters: [errcheck]
    - text: "Error return value of `table\\.Append`"
      linters: [errcheck]
    - text: "Error return value of `table\\.Render`"
      linters: [errcheck]
    - text: "Error return value of `ignore\\.Load`"
      linters: [errcheck]
    - text: "Error return value of `g\\.Wait`"
      linters: [errcheck]
    - text: "Error return value of `json\\.MarshalIndent`"
      linters: [errcheck]
    - text: "Error return value of `os\\.WriteFile`"
      linters: [errcheck]
    - text: "Error return value of `os\\.UserHomeDir`"
      linters: [errcheck]
    - text: "Error return value of `f\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `r\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `rc\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `gz\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `file\\.Close`"
      linters: [errcheck]
    - text: "Error return value of `os\\.RemoveAll`"
      linters: [errcheck]
    - text: "Error return value of `.*\\.MarkDeprecated`"
      linters: [errcheck]
    - text: "Error return value of `doublestar\\.Match`"
      linters: [errcheck]
    - text: "Error return value of `filepath\\.WalkDir`"
      linters: [errcheck]
    # CLI operations that should be best-effort
    - text: "Error return value of `.*\\.GetString`"
      linters: [errcheck]
    - text: "Error return value of `.*\\.GetBool`"
      linters: [errcheck]
    - text: "Error return value of `update\\.Check`"
      linters: [errcheck]
    - text: "Error return value of `engine\\.CountTargets`"
      linters: [errcheck]
    - text: "Error return value of `report\\.LoadBaseline`"
      linters: [errcheck]
    # Test-specific operations that should be best-effort
    - text: "Error return value of `os\\.ReadFile`"
      linters: [errcheck]
    - text: "Error return value of `os\\.MkdirAll`"
      linters: [errcheck]
    - text: "Error return value of `json\\.Marshal`"
      linters: [errcheck]
    - text: "Error return value of `.*\\.Encode`"
      linters: [errcheck]
    - text: "Error return value of `loadCache`"
      linters: [errcheck]
    # Update module should be tolerant of cache failures
    - path: "internal/update/.*\\.go"
      text: "Error return value is not checked"
      linters: [errcheck]
    - text: "Error return value of `writeFixSummary`"
      linters: [errcheck]
    # CLI command files should be more lenient with explicitly ignored errors
    - path: "cmd/redactyl/.*\\.go"
      text: "Error return value is not checked"
      linters: [errcheck]
    # Test files should be more lenient
    - path: ".*_test\\.go"
      linters:
        - errcheck
        - revive
    - path: internal/engine/filters\\.go
      text: "DefaultGeneratedIgnores|defaultExclude"
      linters:
        - revive


