project_name: redactyl

before:
  hooks:
    - go mod tidy

builds:
  - id: redactyl
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.FullCommit}}
      - -X main.date={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: redactyl

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc

release:
  github:
    owner: redactyl
    name: redactyl
  draft: false
  prerelease: auto

