project_name: redactyl

before:
  hooks:
    - go mod tidy

builds:
  - id: redactyl
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/varalys/redactyl/cmd/redactyl.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: redactyl

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc

release:
  github:
    owner: varalys
    name: redactyl
  draft: false
  prerelease: auto

brews:
  - name: redactyl
    repository:
      owner: varalys
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/varalys/redactyl"
    description: "Deep artifact scanner for secrets in containers, Helm charts, and K8s manifests"
    license: "Apache-2.0"
    test: |
      system "#{bin}/redactyl", "version"
    install: |
      bin.install "redactyl"

nfpms:
  - id: default
    package_name: redactyl
    formats: [deb, rpm, apk]
    maintainer: Franz <maintainer@redactyl.io>
    description: Find secrets in your repo with low noise.
    license: Apache-2.0
    homepage: https://github.com/varalys/redactyl
    section: utils
    priority: optional
    contents: []
    bindir: /usr/bin

